@startuml block-05

title 'Class'

class App {
}

class Header {
}


class RESTy {
  ==state==
  # url:string
  # method:string
  # body:string
  # history:object
  # response:object
  ==methods==
  +handleUrl()
  +handleMethod()
  +handleBody()
  +handleSubmit()
  +populate()
}

class History {
  ==props==
  # data:object
  # populate:function
  ==methods==
  +handleClick()
}

class Footer {
}


App --* Header
App --* RESTy
RESTy --* History
History "handleClick()" ..> "populate()" RESTy
App --* Footer

@enduml